use_frameworks!

platform :ios, '8.0'

target 'IRAppearance_Example' do
  pod 'IRAppearance', :path => '../'

  target 'IRAppearance_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
